-- COMANDOS AVG, SUM, COUNT, MAX, MIN, UPPER E LOWER

-- AVG: GERAR MÉDIA DOS DADOS
-- SUM: SOMANDO DADOS DE UMA COLUNA
-- COUNT: CONTAR REGISTROS
-- MAX E MIN: PEGAR VALORES MÁXIMOS E MÍNIMOS
-- UPPER E LOWER: CONVERTER TEXTO PARA MAIÚSCULO E MINPUSCULO

-- ####### AVG ########

SELECT * FROM ALUNO;

-- ADICIONAR A COLUNA PESO

ALTER TABLE ALUNO ADD PESO NUMBER;


-- ATUALIZAR A COLUNA PESO DE CADA REGISTRO

UPDATE ALUNO
SET PESO = 94
WHERE ID_ALUNO = 2;


-- VER A MÉDIA DE TODOS OS REGISTROS DA COLUNA PESO
-- DENTRO DOS PARÊNTESES, COLOCO A COLUNA QUE QUERO SABER A MÉDIA.

SELECT AVG(PESO) FROM ALUNO;

-- VER A MÉDIA DO SOMENTE DO ID_ALUNO 1 A 3

SELECT AVG(PESO) FROM ALUNO WHERE ID_ALUNO BETWEEN 1 AND 3;

-- ##### SUM #####

SELECT * FROM ALUNO;

-- SOMAREMOS TODOS OS VALORES DA COLUNA PESO

SELECT SUM(PESO) FROM ALUNO;

-- PODEMOS DAR NOME AS COLUNAS COM AJUDA DO ASS

SELECT SUM(PESO) AS TOTAL_PESO FROM ALUNO;


-- ##### COUNT #####

-- CONTANDO O TOTAL DE REGISTROS DA TABELA ALUNO

SELECT COUNT(*) FROM ALUNO;


-- CONTANDO TODOS OS REGISTROS DA COLUNA NOME_ALUNO

SELECT COUNT(NOME_ALUNO) FROM ALUNO;

-- ##### MAX E MIN #####

-- PEGANDO O VALOR MÁXIMO DA COLUNA PESO

SELECT MAX(PESO) FROM ALUNO;

-- PEGANDO O VALOR MÍNIMO DA COLUNA PESO

SELECT MIN(PESO) FROM ALUNO;


-- ATENÇÃO: PODEMOS PEGAR O VALOR MAX E MIN DE TEXTOS

SELECT MAX(NOME_ALUNO) FROM ALUNO;
SELECT MIN(NOME_ALUNO) FROM ALUNO;


-- ##### UPPER E LOWER #####

-- TRANSFORMANDO A COLUNA NOME_ALUNNO EM MAIÚSCULO
SELECT UPPER(NOME_ALUNO) FROM ALUNO;

-- TRANSFORMANDO A COLUNA NOME_ALUNNO EM MINÚSCULO
SELECT LOWER(NOME_ALUNO) FROM ALUNO;
 