-- COMANDOS ORDER BY E WHERE

-- ORDER BY: ORDENA OS DADOS DE FORMA CRESCENTE OU DECRESCENTE.
-- WHERE: FILTRA A BUSCA DE DADOS.

-- VER OS REGISTROS DA TABELA ALUNO

SELECT * FROM ALUNO;

-- ORDER BY CRESCENTE

SELECT * FROM ALUNO
ORDER BY NOME_ALUNO;

-- ORDER BY DESCRESCENTE

SELECT * FROM ALUNO
ORDER BY NOME_ALUNO DESC;


-- WHERE

-- SELECIONAR OS ALUNOS ONDE O SEXO É MASCULINO

SELECT * FROM ALUNO
WHERE SEXO_ALUNO = 'M';

-- ATENÇÃO: O SQL ORACLE É CASE SENSITIVE, OU SEJA, DIFERENCIA MAIÚSCULO DE MINÚSCULO.

-- ATENÇÃO: A COLUNA SEXO_ALUNO É DO TIPO DE VARCHAR (TEXTO), ENTÃO, NO FILTRO O
-- M DEVE ESTAR ENTRE ASPAS SIMPLES.

-- SELECIONAR OS ALUNOS ONDE O ID É IGUAL A 2

SELECT * FROM ALUNO
WHERE ID_ALUNO = 2;

-- ATENÇÃO: A COLUNA ID_ALUNO É DO TIPO NUMBER, ENTÃO NO FILTRO, O VALOR 2 NÃO PODE ESTAR ENTRE ASPAS

-- PODEMOS APRIMORAR O FILTRO USANDO OPERADORES

-- MAIOR >
-- MENOR <
-- DIFERENTE <>
-- AND
-- OR
-- IN
-- BETWEEN
-- LIKE


-- SELECIONE OS ALUNOS ONDE O ID É MAIOR QUE 3

SELECT * FROM ALUNO
WHERE ID_ALUNO > 3;

-- SELECIONE OS ALUNOS ONDE O ID É MENOR QUE 3

SELECT * FROM ALUNO
WHERE ID_ALUNO < 3;

-- SELECIONE OS ALUNO ONDE O SEXO É DIFERENTE DE MASCULINO

SELECT * FROM ALUNO
WHERE SEXO_ALUNO <> 'M';

-- SELECIONE OS ALUNOS ONDE O SEXO É MASCULINO E O ID É MENOR QUE 3

SELECT * FROM ALUNO
WHERE SEXO_ALUNO = 'M' AND ID_ALUNO < 3;

-- SELECIONE OS ALUNOS ONDE O ID É 2 OU 4 ( O OR PERMITE BUSCAR REGISTROS QUE ATENDEM
-- PELO MENOS UMA DAS CONDIÇÕES ESPECIFICADAS.

SELECT * FROM ALUNO
WHERE ID_ALUNO = 2 OR ID_ALUNO = 4;

-- SELECIONE OS ALUNOS ONDE OS VALORES 1 E 2 ESTEJAM CONTIDOS NA COLUNA ID_ALUNO

SELECT * FROM ALUNO
WHERE ID_ALUNO IN (1,2);


-- SELECIONE OS ALUNOS ONDE O VALOR DA COLUNA ID_ALUN O SEJA ENTRE 2 E 4

SELECCT * FROM ALUNO
WHERE ID_ALUNO BETWEEN 2 AND 4;

-- SELECIONEOS ALUNOS ONDE NOME_ALUNO COMECE COM A LETRA C
-- O LIKE É ÚTIL QUANDO VOCÊ NÃO SABE O VALOR EXATO, MAS TEM UMA IDEIA DE COMO
-- ELE COMEÇA, TERMINA OU SE PARECE.

SELECT * FROM ALUNO
WHERE NOME_ALUNO LIKE 'L%';

-- SELECIONE OS ALUNOS ONDE NOME_ALUNO TERMINE COM A LETRA O
-- AQUI O PERCENTUAL REPRESENTA O INÍCIO DA PALAVRA

SELECT * FROM ALUNO
WHERE NOME_ALUNO LIKE '%o';

-- ATENÇÃO: NO LIKE IMPORTA SE A LETRA É MAIÚSCULA OU MINÚSCULA.
