-- ####### CONCATENANDO COLUNAS COM O PIPE #######

-- CONCATENAR SIGNIFICA JUNTAR

SELECT * FROM ALUNO;

SELECT NOME_ALUNO, CIDADE_ALUNO FROM ALUNO;

-- SE QUISERMOS JUNTAR AS COLUNAS EM UMA SÓ
-- USAMOS O PIPE || ENTRE AS COLUNAS

SELECT NOME_ALUNO || CIDADE_ALUNO FROM ALUNO; -- ESSA JUNÇÃO CHAMAMOS DE CONCATENAÇÃO

-- AGORA, IREMOS DAR UM NOME PARA ESSA COLUNA
-- PRA ISSO, USAMOS O AS

SELECT NOME_ALUNO || CIDADE_ALUNO AS NOME_CIDADE FROM ALUNO;


-- AGORA QUEREMOS QUE ENTRE OS DADOS NOME E CIDADE TENHA UM TRAÇO
-- COLOCAMOS ESSE TRAÇO DENTRO DE ASPAS SIMPLES E ENTRE DOIS PIPES
-- PODENDO TAMBÉM USAR OUTROS CARACTERES E/OU ESPAÇO EM BRANCO

SELECT NOME_ALUNO || '-' || CIDADE_ALUNO AS NOME_CIDADE FROM ALUNO;

SELECT NOME_ALUNO || ' ' || CIDADE_ALUNO AS NOME_CIDADE FROM ALUNO;


-- ####### MODIFICANDO TAMANHO/TIPO DA COLUNA COM ALTER TABLE #######

DESC ALUNO;

-- AUMENTAR O TAMANHO DA COLUNA CIDADE_ALUNO PARA 60

ALTER TABLE ALUNO MODIFY CIDADE_ALUNO VARCHAR2(60);


-- ALTERANDO O TIPO DA COLUNA DATA_NASC_ALUNO PARA DATE
-- OBSERVAÇÃO: A COLUNA DEVE ESTAR VAZIA

ALTER TABLE ALUNO MODIFY DATA_NASC_ALUNO DATE;



-- ####### APAGANDO UMA COLUNA DA TABELA COM ALTER TABLE DROP #######

-- APAGAR A COLUNA CIDADE_ALUNO

ALTER TABLE ALUNO DROP (CIDADE_ALUNO);


-- ####### DELETAR REGISTROS DA TABELA COM DELETE #######

-- DELETAR O REGISTRO EM QUE O ID_ALUNO É IGUAL A 2

DELETE FROM ALUNO WHERE ID_ALUNO = 2;

SELECT * FROM ALUNO;

-- ATENÇÃO: O DELETE PODE SER DESFEITO COM O ROLLBACK

ROLLBACK;

-- ATENÇÃO: APÓS DELETAR, EXECUTE O COMMIT SE VOCÊ DESEJA SALVAR ESTA AÇÃO


-- ####### EXCLUIR TABLEA COM DROP TABLE #######

-- PRIMEIRO VAMOS CRIAR UMA TABELA

CREATE TABLE ESCOLAS (
    ID_ESCOLA NUMBER,
    NOME_ESCOLA VARCHAR2(50),
    CNPJ_ESCOLA NUMBER
);


SELECT * FROM ESCOLAS;

DESC ESCOLAS;

-- INSERIR REGISTROS NA TABELA ESCOLAS

INSERT INTO ESCOLAS (ID_ESCOLA, NOME_ESCOLA, CNPJ_ESCOLA)
VALUES (2, 'IRINEU PINTO', 5452142443);


-- AGORA, IREMOS EXCLUIR A TABELA ESCCOLAS

DROP TABLE ESCOLAS;














