SELECT * FROM ALUNOS;

DROP TABLE ALUNOS;

alter TABLE aluno RENAME to alunos;




-- ######  AGRUPANDO REGISTROS COM GROUP BY  ######

-- VER REGISTROS NA TABELA ALUNOS

SELECT * FROM ALUNOS;

INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, SEXO_ALUNO, DATA_NASC_ALUNO)
VALUES (3, 'Antonio Carlos', 'M', '25/12/1994');

INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, SEXO_ALUNO, DATA_NASC_ALUNO)
VALUES (4, 'Maria Carla', 'F', '15/10/1992');

INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, SEXO_ALUNO, DATA_NASC_ALUNO)
VALUES (5, 'Eduardo Firmino', 'M', '10/12/1996');

INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, SEXO_ALUNO, DATA_NASC_ALUNO)
VALUES (6, 'Adriana Melyssa', 'F', '08/07/1998');



select * from alunos;


DELETE FROM ALUNOS
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM ALUNOS
    GROUP BY ID_ALUNO, NOME_ALUNO,
    SEXO_ALUNO, DATA_NASC_ALUNO
);



-- VER REGISTROS NA TABELA ALUNOS

SELECT * FROM ALUNOS;

SELECT CIDADE_ALUNO FROM ALUNOS;

SELECT DISTINCT(CIDADE_ALUNO) FROM ALUNOS; -- ATENÇÃO: AS DUPLICIDADES NÃO SERÃO REMOVIDAS DA TABELA,
-- SOMENTE NAS CONSULTAS


-- AGRUPAR REGISTROS DA COLUNA CIDADE_ALUNO

SELECT CIDADE_ALUNO FROM ALUNOS GROUP BY CIDADE_ALUNO;

ALTER TABLE ALUNOS ADD CIDADE_ALUNO VARCHAR2(50);

UPDATE ALUNOS
SET CIDADE_ALUNO = 'MANAUS'
WHERE ID_ALUNO = 1;

--- 

UPDATE ALUNOS
SET PESO = 75
WHERE ID_ALUNO = 4;


-------------------------------------------------------

SELECT * FROM ALUNOS;

-- AGRUPAR REGISTROS DA COLUNA CIDADE_ALUNO
SELECT CIDADE_ALUNO FROM ALUNOS GROUP BY CIDADE_ALUNO;


-- AGRUPAR REGISTRO DA COLUNA CIDADE_ALUNO E CONTAR
SELECT CIDADE_ALUNO, COUNT(*) FROM ALUNOS GROUP BY CIDADE_ALUNO;


-- PODEMOS MUDAR O NOME DA COLUNA COM AS
-- ATENÇÃO: O AS É SOMENTE UM APELIDO


SELECT CIDADE_ALUNO AS CIDADE, COUNT(*) AS QUANTIDADE FROM ALUNOS GROUP BY CIDADE_ALUNO;

-- PODEMOS USAR OUTRAS FUNÇÕES: COUNT, SUM, AVG, MAX, MIN...
-- AGRUPAR REGISTROS DA COLUNA CIDADE_ALUNO E SOMAR PESO_ALUNO

SELECT CIDADE_ALUNO AS CIDADE, SUM(PESO) AS TOTAL_PESO FROM ALUNOS GROUP BY CIDADE_ALUNO;


-- PODEMOS INSERIR O ORDER BY PARA ORDENAR A COLUNA
-- O 1 SIGNIFICA QUE OS REGISTROS SERÃO ORDENADOS PELA PRIMEIRA COLUNA DO SELECT
SELECT CIDADE_ALUNO AS CIDADE, SUM(PESO) AS TOTAL_PESO FROM ALUNOS GROUP BY CIDADE_ALUNO ORDER BY 1;


DESC ALUNOS;

-----------------------------

-- ###### TRAZENDO 2 OU MAIS RESULTADOS NO SELECT COM O UNION ######

-- CRIAR TABELA PROFESSORES

CREATE TABLE PROFESSORES (
    ID_PROF     NUMBER,
    NOME_PROF   VARCHAR2(50),
    CIDADE_PROF VARCHAR2(50)
);

-- INSERIR REGISTROS NA TABELA PROFESSORES

INSERT INTO PROFESSORES (ID_PROF, NOME_PROF, CIDADE_PROF)
VALUES (2, 'CARLOS EDUARDO', 'JOÃO PESSOA');

-- VER REGISTROS DA TABELA PROFESSORES

SELECT * FROM PROFESSORES;

-- VER REGISTROS DA TABELA ALUNOS

SELECT * FROM ALUNOS;

-- TRAZENDO A COLUNA CIDADE DAS TABELAS ALUNOS E PROFESSORES DE UMA VEZ

SELECT CIDADE_ALUNO FROM ALUNOS
UNION
SELECT CIDADE_PROF FROM PROFESSORES;

-- O UNION ALL TRAS TODOS OS REGISSTROS, INCLUSIVE OS DUPLICADOS

SELECT CIDADE_ALUNO FROM ALUNOS
UNION ALL
SELECT CIDADE_PROF FROM PROFESSORES;


-----------------------


-- ###### SUBQUERY - SUBSELECT OU SUBCONSULTA ######

-- UMA SUBQUERY É UMA INSTRUÇÃO DE TIPO SELECT DENTRO DE OUTRA INSTRUÇÃO SQL
-- UM POUCO CONFUSO, NÉ? MAS IREMOS ENTENDER MELHOR FAZENDO EM EXEMPLOS

-- VER REGISTROS DA TABELA ALUNOS
SELECT * FROM ALUNOS;

-- VER APENAS A COLUNA PESO DA TABELA ALUNOS
SELECT PESO FROM ALUNOS;


-- VER A COLUNA PESO SOMENTE DA ALUNA MARIA CARLA

SELECT PESO FROM ALUNOS
WHERE NOME_ALUNO = 'Maria Carla';

-- VER AS COLUNAS NOME E PESO ONDE PESO_ALUNO É MAIOR QUE 94

SELECT NOME_ALUNO, PESO FROM ALUNOS
WHERE PESO > 94;


-- ATENÇÃO: ESSE SELECT EQUIVALE A 99
-- SELECT PESO FROM ALUNOS WHERE NOME_ALUNO = 'Maria Carla'; => 94


-- É RETORNADO O NOME E PESO DE TODOS OS ALUNOS QUE PESAM MAIS QUE A ALUNA MARIA CARLA
SELECT NOME_ALUNO, PESO FROM ALUNOS
WHERE PESO > (SELECT PESO FROM ALUNOS WHERE NOME_ALUNO = 'Maria Carla'); -- >>>
-- ESSE SELECT EQUIVALE A 94
   



