/*
OS TIPOS DE DADOS E CARACTERES:

CHAR
NCHAR
NVARCHAR2
VARCHAR2
VARCHAR -- LETRAS, NÚMEROS, SÍMBOLOS
LONG
RAW
LONG RAW

OS TIPOS DE DADOS NUMÉRICOS:

NUMBER
INT
DECIMAL
BINARY_FLOAT
BINARY_DOUBLE

OS TIPOS DE DADOS DE DATA E HORA:

DATE
TIMESTAMP
TIMESTAMP WITH TIME ZONE
TIMESTAMP WITH LOCAL TIME ZONE
INTERVAL












CREATE TABLE TB_CATEGORIAS(CODIGO_CA INT, DESCRIPTION_CA VARCHAR(30));

CREATE TABLE TB_MEDIDAS(CODIGO_ME NUMBER(3,0),ABREVIATURA_ME VARCHAR2(3), DESCRIPTION_ME VARCHAR2(20));


CREATE TABLE TB_ARTICULOS(CODIGO_AR NUMBER(5,0),
                         DESCRIPTION_AR VARCHAR2(50),
                         MARCA_AR VARCHAR2(30),
                         CODIGO_ME NUMBER(3,0),
                         CODIGO_CA NUMBER(4,0),
                         DATA__ING DATE,
                         ESTOQUE_ATUAL DECIMAL(10,2));



DROP TABLE TB_MEDIDAS;
DROP TABLE TB_CATEGORIAS;
DROP TABLE TB_ARTICULOS;



CREATE TABLE TB_CATEGORIAS(CODIGO_CA NUMBER(4,0), DESCRIPTION_CA VARCHAR2(30));


CREATE TABLE TB_MEDIDAS(CODIGO_ME NUMBER(3,0),
                       ABREVIATURA_ME VARCHAR2(3),
                       DESCRIPTION_ME VARCHAR(20));


CREATE TABLE TB_ARTIGOS(CODIGO_AR NUMBER(6,0),
                        DESCRIPTION_AR VARCHAR2(50),
                        MARCA_AR VARCHAR2(30));


ALTER TABLE TB_MEDIDAS MODIFY (CODIGO_ME NOT NULL);

ALTER TABLE TB_ARTIGOS MODIFY (CODIGO_AR NOT NULL);


ALTER TABLE TB_MEDIDAS MODIFY DESCRIPTION_ME VARCHAR2(30);


ALTER TABLE TB_ARTIGOS DROP COLUMN MARCA_AR;


ALTER TABLE TB_ARTIGOS MODIFY CODIGO_AR NUMBER(6,0) DEFAULT 0;

ALTER TABLE TB_CATEGORIAS MODIFY CODIGO_CA NUMBER(4,0) DEFAULT 0;

ALTER TABLE TB_MEDIDAS MODIFY CODIGO_ME NUMBER(3,0) DEFAULT 0;

ALTER TABLE TB_ARTIGOS ADD MARCA_AR VARCHAR2(30);

ALTER TABLE TB_ARTIGOS ADD (CODIGO_ME NUMBER(3,0), CODIGO_CA NUMBER(4,0));






ALTER TABLE TB_ARTIGOS ADD PRIMARY KEY (CODIGO_AR);


ALTER TABLE TB_CATEGORIAS ADD PRIMARY KEY (CODIGO_CA);


ALTER TABLE TB_MEDIDAS ADD PRIMARY KEY (CODIGO_ME);




ALTER TABLE TB_ARTIGOS
ADD CONSTRAINT FK_01
FOREIGN KEY (CODIGO_ME)
REFERENCES TB_MEDIDAS (CODIGO_ME);


ALTER TABLE TB_ARTIGOS
ADD CONSTRAINT FK_02
FOREIGN KEY (CODIGO_CA)
REFERENCES TB_CATEGORIAS (CODIGO_CA);


CREATE TABLE TB_ARMAZÉM(CODIGO_AZ NUMBER(2,0) GENERATED ALWAYS AS IDENTITY,
                       DESCRIPTION_AZ VARCHAR2(30));
*/

-- INSERINDO INFORMAÇÕES PARA CATEGORIAS

INSERT INTO TB_CATEGORIAS(CODIGO_CA, DESCRIPTION_CA)
                         VALUES(1, 'OFICINAS');
                         
                         
                         
INSERT INTO TB_CATEGORIAS(CODIGO_CA, DESCRIPTION_CA)
                         VALUES(2, 'ESCRITÓRIO');
                         
                
INSERT INTO TB_CATEGORIAS(CODIGO_CA, DESCRIPTION_CA)
                         VALUES(3, 'EVENTOS');                         
                         
                         
-- INSERINDO INFORMAÇÕES PARA MEDIDAS                         
                         
                         
INSERT INTO TB_MEDIDAS(CODIGO_ME, ABREVIATURA_ME, DESCRIPTION_ME)
                         VALUES(1, 'UND','UNIDADES');
                         
INSERT INTO TB_MEDIDAS(CODIGO_ME, ABREVIATURA_ME, DESCRIPTION_ME)
                         VALUES(2, 'KG','QUILOGRAMAS');
                         
INSERT INTO TB_MEDIDAS(CODIGO_ME, ABREVIATURA_ME, DESCRIPTION_ME)
                         VALUES(3, 'MTS', 'METROS'); 
                         
INSERT INTO TB_MEDIDAS(CODIGO_ME, ABREVIATURA_ME, DESCRIPTION_ME)
                         VALUES(4, 'LTS', 'LITROS');                          

-- INSERINDO INFORMAÇÕES PARA ARTIGOS


                        
UPDATE TB_ARTIGOS
SET DESCRIPTION_AR = 'IMPRESSORA'
WHERE CODIGO_AR = 2;
                        
                        
DELETE FROM TB_ARTIGOS
WHERE CODIGO_AR = 3;







UPDATE TB_ARTIGOS SET MARCA_AR='CANON' WHERE CODIGO_AR=2;

UPDATE TB_ARTIGOS SET MARCA_AR='SAMSUNG' WHERE CODIGO_AR IN (3,4);


UPDATE TB_ARTIGOS SET DESCRIPTION_AR=CONCAT('* ',DESCRIPTION_AR)
                WHERE MARCA_AR='ESTRELA;
