-- DESCRIBE, ALTER TABLE ADD, UPDATE E DISTINCT

-- DESCRIBE OU DESC: OBTEM INFORMAÇÕES DA TABELA
-- ALTER TABLE ADD: ADICIONA UMA NOVA COLUNA NA TABELA
-- DISTINCT: ELIMINA REGISTROS DUPLICADOS
-- UPDATE: ALTERAR/ATUALIZAR ALGUM DADO NOS REGISTROS

-- ## DESCRIBE ## --

DESCRIBE ALUNO;

2(20);

-- ## ALTER TABLE ADD ## --

-- ADICIONAR A COLUNA CIDADE NA TABELA ALUNO

-- LÊ-SE: ALTERAR A TABELA ALUNO / ADICIONAR A COLUNA CIDADE_ALUNO

ALTER TABLE ALUNO ADD CIDADE_ALUNO VARCHAR2(20);

-- VAMOS VER COMO FICOU A TABELA

SELECT * FROM ALUNO;

-- ATUALIZAR OS REGISTROS NA COLUNA CIDADE_ALUNO

UPDATE ALUNO
SET CIDADE_ALUNO = 'RECIFE'
WHERE ID_ALUNO = 2;


-- ## DISTINCT ## --

-- COM ESSE SELECT QUEREMOS VER APENAS A COLUNA CIDADE_ALUNO
-- PODEMOS VER QUE TEMOS DUAS CIDADES SE REPETINDO

SELECT CIDADE_ALUNO FROM ALUNO;

-- COM O DISTINCT PODEMOS REMOVER AS DUPLICIDADES
SELECT DISTINCT(CIDADE_ALUNO) FROM ALUNO;

-- ATENÇÃO: AS DUPLICIDADES NÃO SERÃO REMOVIDAS DA TABELA, SOMENTE NA NOSSA CONSULTA

SELECT * FROM ALUNO;
