
SELECT NEXT_DAY('13/04/2026','TERÇA-FEIRA') FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT SYSTIMESTAMP FROM DUAL;

SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT CONCAT(SYSDATE,'DATA ATUAL') FROM DUAL;

SELECT '13/04/2026' FROM DUAL;


SELECT * FROM TB_ARTIGOS;

UPDATE TB_ARTIGOS SET ATIVO=1;

UPDATE TB_ARTIGOS SET ESTOQUE_ATUAL=0;

UPDATE TB_ARTIGOS SET DATA_INSCRIÇÃO=SYSDATE;



-- RELAÇÃO SELECT INNER JOIN

SELECT TB_CATEGORIAS.CODIGO_CA,
       TB_CATEGORIAS.DESCRIPTION_CA,
       TB_ARTIGOS.DESCRIPTION_AR,
       TB_ARTIGOS.MARCA_AR
FROM TB_CATEGORIAS
LEFT JOIN TB_ARTIGOS ON TB_CATEGORIAS.CODIGO_CA=TB_ARTIGOS.CODIGO_CA;


-- RELAÇÃO DE DADOS SELECT RIGHT JOIN

SELECT A.CODIGO_AR,
       A.DESCRIPTION_AR,
       A.MARCA_AR,
       B.DESCRIPTION_ME
FROM TB_ARTIGOS A
RIGHT JOIN TB_MEDIDAS B ON A.CODIGO_ME=B.CODIGO_ME;

-- RELAÇÃO DE DADOS ORDER BY

  